backend:
    name: git-gateway
    repo: saihaj/punjabi-classes
    branch: master

media_folder: "_images"
publish_mode: editorial_workflow

collections:
    - name: "Class-X"
      label: "Class-X"
      folder: "/Class-X"
      create: true
      slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}