# This is a basic workflow to help you get started with Actions

name: Publish Website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # skips deploymeent if commit message contains "ci skip"
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    
    - name: Test links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: yes

    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: content
        committer_name: saihaj
        commiter_email: saihaj@users.noreply.github.com
      env:
        GITHUB_PAT: ${{ secrets.deploy_access_token }}

